name: chat_app
description: .
publish_to: 'none' 
version: 1.0.1+1
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Localization
  intl: ^0.19.0

  # DI
  get_it: ^8.0.2
  injectable: ^2.5.0

  # State Management
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  # Models Mapping
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Navigation
  auto_route: ^9.2.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  firebase_crashlytics: ^4.1.5
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.6
  firebase_storage: ^12.3.6
  cloud_functions: ^5.1.5
  firebase_remote_config: ^5.1.5

  # Storage
  shared_preferences: ^2.3.3

  # Network
  dio: ^5.7.0

  # Other
  either_dart: ^1.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  another_flushbar: ^1.12.31-dev.1
  package_info_plus: ^8.1.3
  uuid: ^4.5.1
  useful_extensions: ^0.0.1
  sign_in_button: ^3.2.0
  permission_handler: ^11.3.1
  keyboard_height_plugin: ^0.1.5
  flutter_markdown: ^0.7.4+3
  http: ^1.2.2
  rxdart: ^0.28.0
  image_picker: ^1.1.2
  collection: ^1.18.0
  screen_state: ^4.0.0
  restart_app: ^1.3.2
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  flutter_branch_sdk: ^8.2.0
  share_plus: ^10.1.4
  tflite_flutter: ^0.11.0
  # tflite_flutter_helper:
  #   path: packages/tflite_flutter_helper

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  auto_route_generator: ^9.0.0
  lint: ^2.3.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2
  mockito: ^5.0.16
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/tic_tac_toe.png
    - assets/tflite/tic_tac_toe_model.tflite

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1a1a1a"
  image: assets/icons/tic_tac_toe.png

flutter_launcher_icons:
  image_path: "assets/icons/tic_tac_toe.png"
  android: "im_logo"
  ios: true
  remove_alpha_ios: true

flutter_intl: 
  enabled: true