// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDILFK5WGoZ427oppjgDjmZbYwHprVg9yA',
    appId: '1:212552143741:web:fea1d2bb87a8c2c396b214',
    messagingSenderId: '212552143741',
    projectId: 'flutter-chat-acda6',
    authDomain: 'flutter-chat-acda6.firebaseapp.com',
    storageBucket: 'flutter-chat-acda6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRW-CbprKEUJCBmJ2OjQHedZEw80t2biU',
    appId: '1:212552143741:android:6a10600479ade86f96b214',
    messagingSenderId: '212552143741',
    projectId: 'flutter-chat-acda6',
    storageBucket: 'flutter-chat-acda6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzPKCQt7VV9e51G_fwUczSuoVgJjzPGQQ',
    appId: '1:212552143741:ios:d814fdaac50568ff96b214',
    messagingSenderId: '212552143741',
    projectId: 'flutter-chat-acda6',
    storageBucket: 'flutter-chat-acda6.appspot.com',
    androidClientId: '212552143741-vprtb3c367vujrlmtttc7ion1ejhl9vm.apps.googleusercontent.com',
    iosClientId: '212552143741-s5eokmrgt77lc3gau7ua31vn9n3ql1lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat_app',
  );
}
